### ISSUE TITLE
Recommendation: don't use `marky-markdown`

### ISSUE THREAD

**Issue by demoneaux** [lodash/lodash.github.io#21]
`marky-markdown` seems to do a lot of specialised stuff related to npm which isn't really necessary. For example it wraps all the headings in `<a>`s, which isn’t necessary for our code. I think we can probably just use `markdown-it` and `highlights`, along with some code to customise it. Maybe cheerio also if we need to modify generated html output. What do y'all think?

**Comment by demoneaux** [comment]
Also I think the current process for generating the latest docs is a little weird, as that code should probably be in this repo. Originally, I thought perhaps a copy of lodash.js and the docdown generated markdown for each new version could be placed in this repo, and the documentation page will then be generated for each version. This would also allow documentation for a specific version to include that lodash version, instead of the latest version.

**Comment by jdalton** [comment]
No worries, I've reported the bug to [marky-markdown](https://github.com/npm/marky-markdown/issues/200). I'm with things here being essentially static.

**Comment by revin** [comment]
oh hey all I saw this linked from the issue @jdalton reported in marky-markdown; marky's goal over time is to basically be a copy of what github does when it renders markdown, so that's the (moving?) roadmap. If your needs are roughly close to that, feel free to open bugs or ask for various things to be added as runtime options or whatever; if not, then yes you're probably best off using markdown-it directly, plus whatever [plugins](https://www.npmjs.com/browse/keyword/markdown-it-plugin) you might need.
